### ISSUE TITLE
Make setting button rebindable

### ISSUE THREAD

**Issue by Desoroxxx** [alejandrocoria/MapFrontiers#56]
I use F8 for the advancement screen, and this mod takes priority and it does not seem to be rebindable

**Comment by alejandrocoria** [comment]
It is rebindable in Fabric and should be in Forge and NeoForge, but it isn't for some reason. Let me check.

**Comment by alejandrocoria** [comment]
Fixed in 1.21-2.6.0p1.

Thanks for letting me know!

**Comment by RosaryMala** [comment]
This is still broken on MC 1.20.1, mod version 2.6.1, forge.

**Comment by alejandrocoria** [comment]
Fixed in 1.20.1-2.6.1p1-forge.
Thanks so much for letting me know!
